- name: Dotfiles setup
  tags:
    - install
    - dotfiles
  block:
    - name: Installing stow and openssh
      become: true
      community.general.pacman:
        name:
          - stow
          - openssh

    - name: Cloning .dotfiles
      ansible.builtin.git:
        repo: "git@github.com:connorjjantzi/dotfiles.git"
        dest: "{{ ansible_env.HOME }}/.dotfiles"
        recursive: true
        update: false
        accept_hostkey: true
        version: main

    - name: Stow dotfiles
      ansible.builtin.shell: cd $HOME/.dotfiles && stow kitty nvim ohmyposh scripts tmux zsh spicetify ags
      # FIX: hypr needs to be stowed but it already is created on install of hyprland
      # don't want to add --adopt because it could ovewrite my configs
