- name: Install hyprland
  tags:
    - install
    - hyprland
  block:
    - name: Install hyprland packages
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - hyprland
          - hyprlock
          - hyprpaper
          - hyprshade-git
          - hyprpicker
          - hypridle
          - xdg-desktop-portal-hyprland
          - xdg-desktop-portal-gtk
          - apple-fonts # hyprlock TODO: need to add install for Suisse Int'l Mono and StretchPro
          - ttf-google-fonts-git # hyprlock fonts
          - pandoc-cli # md to pdf

    - name: Install ags packages
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - aylurs-gtk-shell
          - bun-bin
          - dart-sass
          - fd
          - brightnessctl
          # - swww # don't need, use hyprpaer instaed
          - matugen-bin
          - bluez-utils

    - name: Install optional ags packages
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - fzf
          - hyprpicker
          - slurp
          # - wf-recorder
          - wf-recorder-git
          - wl-clipboard
          - wayshot
          # - flameshot
          - swappy
          - gvfs

    - name: Install fonts and themes
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - ttf-maple
          - inter-font
          - papirus-icon-theme-git

    - name: Create user units for hyprshade
      ansible.builtin.command:
        cmd: "hyprshade install"
        creates: "{{ ansible_env.HOME }}/.config/systemd/user/hyprshade.timer"

    - name: Enable and start hyprshade timer for the current user
      ansible.builtin.systemd:
        name: hyprshade.timer
        state: started
        enabled: true
        scope: user

    - name: Install other packages
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - wl-clip-persist
          - wl-clipboard
          - cliphist
          - playerctl
          # - dunst
          - pipewire
          - wireplumber
          # - polkit-kde-agent
          - polkit-gnome
          - qt5-wayland
          - qt6-wayland
          # - kwayland5
          - qt5-x11extras
          - usbutils
          - nwg-look
          - btrfs-progs
          - timeshift
          - xorg-xhost
          - grub-btrfs
          - inotify-tools
          - grim

    - name: Enable and start cronie service
      ansible.builtin.systemd:
        name: cronie.service
        state: started
        enabled: true

    # NOTE: Need to run `# systemctl edit --full grub-btrfsd` and `replace grub-btrfsd --syslog /.snapshots with grub-btrfsd --syslog -t` SEE: https://wiki.archlinux.org/title/Timeshift
    - name: Enable and start GRUB btrfs service
      ansible.builtin.systemd:
        name: grub-btrfsd.service
        enabled: true

    # NOTE: Not sure where to put this
    - name: Add emojis
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - noto-fonts-emoji

    # NOTE: Install sugar-dark and [Theme]
    #                              Current=sugar-dark
    # to /etc/sddm.conf
    # also set ForceHideCompletePassword=true
