- name: Install other packages
  tags:
    - install
    - packages
  block:
    - name: Install packages
      become: true
      kewlfft.aur.aur:
        use: yay
        name:
          - github-cli
          - discord
          - kitty
          - firefox
