- name: Nvidia setup
  tags:
    - nvidia
  block:
    - name: Install nvidia packages
      become: true
      pacman:
        name: 
          - nvidia
          - nvidia-utils
          - lib32-nvidia-utils
          - egl-wayland

    - name: Create modprope config
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/modprobe.d/nvidia.conf"
        line: "options nvidia_drm modeset=1 fbdev=1"
        create: true
        mode: "0644"

    - name: Add nvidia modules
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/mkinitcpio.conf"
        regexp: "MODULES=()"
        line: "MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)"
