- name: Neovim setup
  tags:
    - install
    - nvim
  block:
    - name: Install neovim and packages for LazyVim and plugins
      kewlfft.aur.aur:
        use: yay
        state: present
        name:
          - neovim-git
          - ttf-jetbrains-mono-nerd
          - lazygit
          - ripgrep
          - fd
          - fzf
          - bat
          - git-delta
          - chafa
          - viu
          - openslide
          - poppler-glib
          - wget
          - unzip
          - xdg-utils
          - lua51
          - python-pipenv
          - python-pynvim
          - jq
          - python-pylatexenc
          - github-cli
          - biber
          - texlive-bin
          - texlive-binextra
          - texlive-latex
          - tree-sitter-cli

    - name: Install ueberzugpp
      kewlfft.aur.aur:
        use: yay
        state: present
        name: ueberzugpp

    - name: Install languages for Mason
      become: true
      community.general.pacman:
        name:
          - luarocks
          - composer
          - php
          - jdk-openjdk
          - julia
