- name: Productivity tools setup
  tags:
    - install
    - productivity
  block:
    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - zoxide
          - tmux
          - tldr
          - man-db
          - eza
          - interception-caps2esc
          - fastfetch

    - name: Install aur packages
      kewlfft.aur.aur:
        use: yay
        name:
          - lazydocker

    - name: Check if TPM folder exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm"
      register: tpm_folder

    - name: Clone TPM repo
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm"
        version: master

    - name: Install TPM plugins
      ansible.builtin.shell: |
        "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm/bin/install_plugins"
      when: not tpm_folder.stat.exists
      changed_when: false
