- name: Productivity tools setup
  tags:
    - install
    - productivity
  block:
    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - zoxide
          - tmux
          - tldr
          - man-db
          - eza
          - interception-caps2esc # TODO: Add config file at /etc/interception/udevmon.yaml and sudo systemctl enable --now udevmon
          - fastfetch
          - yazi
          - btop
          # - iw # TODO: WIFI setup not sure if needed
          - terraform
          - bear # Used for Makefile to get compile_commands.json
          - imagemagick # Image manipulation
          - gimp

    - name: Install aur packages
      kewlfft.aur.aur:
        use: yay
        name:
          - vscode-codicons-git # VSCode font for clangd_extensions.nvim
          - stripe-cli
          - aws-cli-v2
          - lazydocker

    - name: Check if TPM folder exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm"
      register: tpm_folder

    - name: Clone TPM repo
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm"
        version: master

    - name: Install TPM plugins
      ansible.builtin.shell: |
        "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm/bin/install_plugins"
      when: not tpm_folder.stat.exists
      changed_when: false
