- name: SSH keys setup
  tags:
    - install
    - dotfiles
    - ssh
    - wsl
  block:
    - name: Ensure the local .ssh directory exists
      ansible.builtin.file:
        path: "{{ dest_key_dir }}"
        state: directory
        mode: "0700"

    - name: Copy private SSH keys to local .ssh directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ dest_key_dir }}/"
        mode: "0600"
      with_fileglob:
        - "{{ source_key_dir }}/id_*"
      when: "not item.endswith('.pub')"

    - name: Copy public SSH keys to local .ssh directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ dest_key_dir }}/"
        mode: "0644"
      with_fileglob:
        - "{{ source_key_dir }}/id_*.pub"

    - name: Copy SSH config file to local .ssh directory
      ansible.builtin.copy:
        src: "{{ source_key_dir }}/config"
        dest: "{{ dest_key_dir }}/config"
        mode: "0600"
